---
output:
  html_document: default
  word_document: default
---
# Data sources

As mentioned in the introduction, our data collector/parser program accepts a stream of tweets and extracts the data of interest into a format that is easier to work with in R. Below is a raw streamed tweet as it comes from Twitter. Note that it includes both the user who tweeted and the information on the original tweet that may have been rewteeted. In addition, the information on both users (e.g. follower count, verification status, etc.) is contained in the message: The tweeting user and the user being retweeted.

**Raw Twitter Stream Output**

|   {
|    "created_at": "Fri Apr 09 14:01:50 +0000 2021",
|    "id": 1380521336418697218,
|    "id_str": "1380521336418697218",
|    "text": "RT @alygur: time to share this again to debunk ramadhan\/fasting myths!!!!! https:\/\/t.co\/FJyA2QzR6v",
|    "source": "\u003ca href=\"https:\/\/mobile.twitter.com\" rel=\"nofollow\"\u003eTwitter Web App\u003c\/a\u003e",
|    "truncated": false,
|    "in_reply_to_status_id": null,
|    "in_reply_to_status_id_str": null,
|    "in_reply_to_user_id": null,
|    "in_reply_to_user_id_str": null,
|    "in_reply_to_screen_name": null,
|    "user": {
|        "id": 1344349183,
|        "id_str": "1344349183",
|        "name": "\u043d\u03b1\u0455\u0454\u03c3",
|        "screen_name": "amzaranuarr",
|        "location": "Sp",
|        "url": "https:\/\/youtu.be\/nTadgJizwlA",
|        "description": "20 . Shinzo wo Sasageyo!",
|        "translator_type": "none",
|        "protected": false,
|        "verified": false,
|        "followers_count": 367,
|        "friends_count": 588,
|        "listed_count": 1,
|        "favourites_count": 14723,
|        "statuses_count": 13514,
|        "created_at": "Thu Apr 11 13:02:35 +0000 2013",
|        "utc_offset": null,
|        "time_zone": null,
|        "geo_enabled": true,
|        "lang": null,
|        "contributors_enabled": false,
|        "is_translator": false,
|        "profile_background_color": "000000",
|        "profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme5\/bg.gif",
|        "profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme5\/bg.gif",
|        "profile_background_tile": false,
|        "profile_link_color": "7FDBB6",
|        "profile_sidebar_border_color": "000000",
|        "profile_sidebar_fill_color": "000000",
|        "profile_text_color": "000000",
|        "profile_use_background_image": false,
|        "profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/1374416579534884864\/KVcZZWsD_normal.jpg",
|        "profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/1374416579534884864\/KVcZZWsD_normal.jpg",
|        "profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/1344349183\/1616120646",
|        "default_profile": false,
|        "default_profile_image": false,
|        "following": null,
|        "follow_request_sent": null,
|        "notifications": null
|    },
|    "geo": null,
|    "coordinates": null,
|    "place": null,
|    "contributors": null,
|    "retweeted_status": {
|        "created_at": "Fri Apr 09 05:52:29 +0000 2021",
|        "id": 1380398187995820037,
|        "id_str": "1380398187995820037",
|        "text": "time to share this again to debunk ramadhan\/fasting myths!!!!! https:\/\/t.co\/FJyA2QzR6v",
|        "display_text_range": [
|            0,
|            62
|        ],
|        "source": "\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
|        "truncated": false,
|        "in_reply_to_status_id": null,
|        "in_reply_to_status_id_str": null,
|        "in_reply_to_user_id": null,
|        "in_reply_to_user_id_str": null,
|        "in_reply_to_screen_name": null,
|        "user": {
|            "id": 436607420,
|            "id_str": "436607420",
|            "name": "aly \u062d\u0644\u0627\u0644 era",
|            "screen_name": "alygur",
|            "location": "she\/her | \ud83c\uddf8\ud83c\uddec",
|            "url": "http:\/\/youtube.com\/alygur",
|            "description": "#NNR ONGOING",
|            "translator_type": "none",
|            "protected": false,
|            "verified": false,
|            "followers_count": 9752,
|            "friends_count": 471,
|            "listed_count": 11,
|            "favourites_count": 57466,
|            "statuses_count": 98848,
|            "created_at": "Wed Dec 14 10:37:03 +0000 2011",
|            "utc_offset": null,
|            "time_zone": null,
|            "geo_enabled": true,
|            "lang": null,
|            "contributors_enabled": false,
|            "is_translator": false,
|            "profile_background_color": "ABB8C2",
|            "profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif",
|            "profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme11\/bg.gif",
|            "profile_background_tile": true,
|            "profile_link_color": "F58EA8",
|            "profile_sidebar_border_color": "FFFFFF",
|            "profile_sidebar_fill_color": "E5507E",
|            "profile_text_color": "362720",
|            "profile_use_background_image": true,
|            "profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/1380402111377068034\/YamOXy0a_normal.jpg",
|            "profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/1380402111377068034\/YamOXy0a_normal.jpg",
|            "profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/436607420\/1608337821",
|            "default_profile": false,
|            "default_profile_image": false,
|            "following": null,
|            "follow_request_sent": null,
|            "notifications": null
|        },
|        "geo": null,
|        "coordinates": null,
|        "place": null,
|        "contributors": null,
|        "is_quote_status": false,
|        "quote_count": 61,
|        "reply_count": 3,
|        "retweet_count": 3138,
|        "favorite_count": 3767,
|        "entities": {
|            "hashtags": [],
|            "urls": [],
|            "user_mentions": [],
|            "symbols": [],
|            "media": [
|                {
|                    "id": 1380398179217108993,
|                    "id_str": "1380398179217108993",
|                    "indices": [
|                        63,
|                        86
|                    ],
|                    "media_url": "http:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                    "media_url_https": "https:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                    "url": "https:\/\/t.co\/FJyA2QzR6v",
|                    "display_url": "pic.twitter.com\/FJyA2QzR6v",
|                    "expanded_url": "https:\/\/twitter.com\/alygur\/status\/1380398187995820037\/photo\/1",
|                    "type": "photo",
|                    "sizes": {
|                        "thumb": {
|                            "w": 150,
|                            "h": 150,
|                            "resize": "crop"
|                        },
|                        "large": {
|                            "w": 828,
|                            "h": 1158,
|                            "resize": "fit"
|                        },
|                        "medium": {
|                            "w": 828,
|                            "h": 1158,
|                            "resize": "fit"
|                        },
|                        "small": {
|                            "w": 486,
|                            "h": 680,
|                            "resize": "fit"
|                        }
|                    }
|                }
|            ]
|        },
|        "extended_entities": {
|            "media": [
|                {
|                    "id": 1380398179217108993,
|                    "id_str": "1380398179217108993",
|                    "indices": [
|                        63,
|                        86
|                    ],
|                    "media_url": "http:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                    "media_url_https": "https:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                    "url": "https:\/\/t.co\/FJyA2QzR6v",
|                    "display_url": "pic.twitter.com\/FJyA2QzR6v",
|                    "expanded_url": "https:\/\/twitter.com\/alygur\/status\/1380398187995820037\/photo\/1",
|                    "type": "photo",
|                    "sizes": {
|                        "thumb": {
|                            "w": 150,
|                            "h": 150,
|                            "resize": "crop"
|                        },
|                        "large": {
|                            "w": 828,
|                            "h": 1158,
|                            "resize": "fit"
|                        },
|                        "medium": {
|                            "w": 828,
|                            "h": 1158,
|                            "resize": "fit"
|                        },
|                        "small": {
|                            "w": 486,
|                            "h": 680,
|                            "resize": "fit"
|                        }
|                    }
|                }
|            ]
|        },
|        "favorited": false,
|        "retweeted": false,
|        "possibly_sensitive": false,
|        "filter_level": "low",
|        "lang": "en"
|    },
|    "is_quote_status": false,
|    "quote_count": 0,
|    "reply_count": 0,
|    "retweet_count": 0,
|    "favorite_count": 0,
|    "entities": {
|        "hashtags": [],
|        "urls": [],
|        "user_mentions": [
|            {
|                "screen_name": "alygur",
|                "name": "aly \u062d\u0644\u0627\u0644 era",
|                "id": 436607420,
|                "id_str": "436607420",
|                "indices": [
|                    3,
|                    10
|                ]
|            }
|        ],
|        "symbols": [],
|        "media": [
|            {
|                "id": 1380398179217108993,
|                "id_str": "1380398179217108993",
|                "indices": [
|                    75,
|                    98
|                ],
|                "media_url": "http:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                "media_url_https": "https:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                "url": "https:\/\/t.co\/FJyA2QzR6v",
|                "display_url": "pic.twitter.com\/FJyA2QzR6v",
|                "expanded_url": "https:\/\/twitter.com\/alygur\/status\/1380398187995820037\/photo\/1",
|                "type": "photo",
|                "sizes": {
|                    "thumb": {
|                        "w": 150,
|                        "h": 150,
|                        "resize": "crop"
|                    },
|                    "large": {
|                        "w": 828,
|                        "h": 1158,
|                        "resize": "fit"
|                    },
|                    "medium": {
|                        "w": 828,
|                        "h": 1158,
|                        "resize": "fit"
|                    },
|                    "small": {
|                        "w": 486,
|                        "h": 680,
|                        "resize": "fit"
|                    }
|                },
|                "source_status_id": 1380398187995820037,
|                "source_status_id_str": "1380398187995820037",
|                "source_user_id": 436607420,
|                "source_user_id_str": "436607420"
|            }
|        ]
|    },
|    "extended_entities": {
|        "media": [
|            {
|                "id": 1380398179217108993,
|                "id_str": "1380398179217108993",
|                "indices": [
|                    75,
|                    98
|                ],
|                "media_url": "http:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                "media_url_https": "https:\/\/pbs.twimg.com\/media\/Eygo1JDU8AEPKUU.jpg",
|                "url": "https:\/\/t.co\/FJyA2QzR6v",
|                "display_url": "pic.twitter.com\/FJyA2QzR6v",
|                "expanded_url": "https:\/\/twitter.com\/alygur\/status\/1380398187995820037\/photo\/1",
|                "type": "photo",
|                "sizes": {
|                    "thumb": {
|                        "w": 150,
|                        "h": 150,
|                        "resize": "crop"
|                    },
|                    "large": {
|                        "w": 828,
|                        "h": 1158,
|                        "resize": "fit"
|                    },
|                    "medium": {
|                        "w": 828,
|                        "h": 1158,
|                        "resize": "fit"
|                    },
|                    "small": {
|                        "w": 486,
|                        "h": 680,
|                        "resize": "fit"
|                    }
|                },
|                "source_status_id": 1380398187995820037,
|                "source_status_id_str": "1380398187995820037",
|                "source_user_id": 436607420,
|                "source_user_id_str": "436607420"
|            }
|        ]
|    },
|    "favorited": false,
|    "retweeted": false,
|    "possibly_sensitive": false,
|    "filter_level": "low",
|    "lang": "en",
|    "timestamp_ms": "1617976910105"
|   }





