# Conclusion

Although we would have liked to demonstrate a clear relationship between the words users employ on Twitter and the various quality variables associated with a Twitter account, the data we collected is insufficient to reach any firm conclusions beyond the one below:

**Verified and longstanding accounts appear to interact in a more superior manner on Twitter**

A deeper analysis of the relationship we set out to explore would require:

1) Extensive collection of data over a much longer time horizon (perhaps, randomly selected weeks and months in a year)
2) Analysis of the Twitter accounts that generated the tweets beyond the usual follower/following/favorite counts. For example, do the users who were classified in the foul category tend to always use such words in all their tweets?
3) Sentiment analysis of collected tweets to more properly gauge context.

Another direction worth exploring is the quality of users and user interactions around specific historical events, such as the Jan 6, 2021 Insurrection. This type of analysis is more difficult to conduct, however, as Twitter significantly limits historical access.


